config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :recipes, only: [:index, :show] do
    resources :saved_recipes, only: [:create]
  end
  resources :saved_recipes, only: [:destroy]
  get 'dashboard', to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'search', to: 'pages#search'
  get 'favourite', to: 'pages#favourite'
  get 'completed', to: 'pages#completed'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :saved_recipes
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/saved_recipe.rb
class SavedRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :recipe_id, uniqueness: {scope: :user_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :saved_recipes
  has_many :recipes, through: :saved_recipes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # app/controllers/application_controller.rb

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'light', only: [:home]
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def index
    @recipes = current_user.recipes
    @saved_recipes = current_user.saved_recipes
  end

  def search
    if params[:query].present?
      @ingredients = Ingredient.search_by_name(params[:query])
    else
      @ingredients = Ingredient.all
    end
  end

  def favourite
    @favourite_recipes = current_user.saved_recipes.where(favourite: true)
  end

  def completed
    @completed_recipes = current_user.saved_recipes.where(completed: true)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @ingredients = ingredients_collection
    @saved_recipes = current_user.saved_recipes
    if params[:query].present?
      @ingredient_ids = params[:query][:ingredient_ids]
      @recipes = find_recipes(@ingredient_ids)
    else
      @recipes = Recipe.all
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = RecipeIngredient.where(recipe_id: params[:id])
    @instructions = @recipe.instructions.split("\\n")
    @saved_recipe = SavedRecipe.where(recipe_id: @recipe.id, user_id: current_user.id)[0]
  end

  private

  def ingredients_collection
    Ingredient.all.map { |ingredient| [ingredient.id, ingredient.name] }
  end

  def find_recipes(ids)
    recipes = []
    Recipe.all.each do |recipe|
      recipes << recipe if id_in_recipe?(recipe, ids)
    end
    recipes
  end

  def id_in_recipe?(recipe, ids)
    recipe_ids = recipe.recipe_ingredients.map { |recipe_ingredient| recipe_ingredient.ingredient_id.to_s }
    recipe_ids << ""
    arr = []
    ids.each do |id|
      if recipe_ids.include?(id)
        arr << true
      else
        arr << false
      end
    end
    arr.all?
  end
end

app/controllers/saved_recipes_controller.rb
class SavedRecipesController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @saved_recipe = SavedRecipe.find_or_create_by(recipe: @recipe, user: current_user)
    if params[:attribute].present?
      @saved_recipe.toggle!(params[:attribute])
    end
    @saved_recipe.recipe = @recipe
    @saved_recipe.user = current_user
    @saved_recipe.save
    render json: @saved_recipe
    # respond_to do |format|
    #   format.js
    # end
    # redirect_back(fallback_location: recipes_path)
  end

  def destroy
    @saved_recipe = SavedRecipe.find(params[:id])
    @saved_recipe.destroy
    redirect_back(fallback_location: recipes_path)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= favicon_link_tag %>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/layouts/light.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= favicon_link_tag %>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/pages/completed.html.erb
<h1><strong>Completed Recipes</strong></h1>
<style>
h1{
  margin-top: 5px;
}
</style>
<% @completed_recipes.each do |completed_recipe| %>
    <div class="recipe-cards-container">
      <%= render 'components/card', recipe: completed_recipe.recipe, saved_recipe: completed_recipe %>
    </div>
<% end %>

app/views/pages/favourite.html.erb
<h1><strong>Favourites Recipes</strong></h1>
<style>
h1{
  margin-top: 5px;
}
</style>
<% @favourite_recipes.each do |favourite_recipe| %>
    <div class="recipe-cards-container">
      <%= render 'components/card', recipe: favourite_recipe.recipe, saved_recipe: favourite_recipe %>
    </div>
<% end %>

app/views/pages/home.html.erb
<div class='banner-container'>
  <div class='banner-container-content text-center'>
    <div class="logo">
      <img src="/assets/chefme_trial_logo2_transparent_no_slogan-d672db6620288e5ae16493b26777b1ba28ebc62b14a5d74dc1583bc1e7e6841d.png" style="margin-top: 50px;width: 240px;height: 135px;">
      <h2>Let your inner chef out</h2>
    </div>
    <div class="p-home" style="margin-top: 200px;">
      <p class='quote'>" No one is born a great cook,</p>
      <p class='quote'>ones learns by doing "</p>
      <p class='quote_author'>- Julia Child</p>
      <p> Choose what to cook with whatever<br>
        you have in your fridge.</p>
    </div>
    <div class="btdiv">
      <%= link_to 'Start Now!', recipes_path , class: 'button home' %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1><strong>Saved Recipes</strong></h1>
<style>
  h1{
    margin-top: 5px;
  }
</style>
<% @recipes.each do |recipe| %>
  <% saved_recipe = @saved_recipes.where(user_id: current_user.id, recipe_id: recipe.id)[0] %>
    <div class="recipe-cards-container">
      <%= render 'components/card', recipe: recipe, saved_recipe: saved_recipe %>
    </div>
<% end %>

app/views/pages/search.html.erb
<div>
  <h1 id='title'>What do you have in your fridge?</h1>
</div>
<div>
  <%= form_tag search_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search for an ingredient"
    %>
    <%= submit_tag "Search", class: "button" %>
  <% end %>
  <div>
    <%# <% @ingredients.each do |ingredient| %>
      <p><%#= ingredient.name %></p>
    <%# end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h5 class='search-header'>What's in your fridge?</h5>
  <div>
    <%= simple_form_for :query, url: recipes_path, method: :get, html: { class: 'search-form' } do |f| %>
      <%= f.input :ingredient_ids, label: false, collection: @ingredients, label_method: :second, value_method: :first, input_html: {multiple: true, data: {controller: 'select2', select2_options_value: {tags: true}}}%>
      <%= f.button :submit, 'Find recipes', class: 'button', style: 'width: 100%; margin: auto;' %>
    <% end %>
  </div>
</div>
<%# <h1>Top results</h1> %>
<% @recipes.each do |recipe| %>
  <% saved_recipe = @saved_recipes.where(user_id: current_user.id, recipe_id: recipe.id)[0] %>
  <div class="recipe-cards-container">
    <%= render 'components/card', recipe: recipe, saved_recipe: saved_recipe %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@recipe.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @recipe.description %>
<% content_for :meta_image, image_path(@recipe.image_url) %>

<div class="container">
  <div class='back-and-icons'>
    <a onclick="window.history.back()" class='back'>
      <i class="fas fa-arrow-left" style='margin-top: 20px;'></i>
    </a>
    <div class='icons' data-controller='card-icons'>
      <% if @saved_recipe %>
        <i class="fas fa-bookmark" data-action='click->card-icons#bookmark' data-saved='<%=@saved_recipe.id%>' data-recipe='<%=@recipe.id%>'></i>
      <% else %>
        <i class="far fa-bookmark" data-action='click->card-icons#bookmark' data-recipe='<%=@recipe.id%>' data-saved='0'></i>
      <% end %>
      <%= link_to recipe_saved_recipes_path(@recipe, attribute: :favourite), method: :post, remote: true do %>
        <% if @saved_recipe && @saved_recipe&.favourite %>
          <i class="fas fa-heart" data-action='click->card-icons#favourite'></i>
        <% else %>
          <i class="far fa-heart" data-action='click->card-icons#favourite'></i>
        <% end %>
      <% end %>
      <%= link_to recipe_saved_recipes_path(@recipe, attribute: :completed), method: :post, remote: true do %>
        <% if @saved_recipe && @saved_recipe&.completed %>
          <i class="fas fa-check-square" data-action='click->card-icons#complete'></i>
        <% else %>
          <i class="far fa-check-square" data-action='click->card-icons#complete'></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <h1 class="name"><%= @recipe.name %></h1>
  <br>
  <center><%=image_tag @recipe.image_url, class: "image"%></center> <br>

  <div class="container-flex">
    <div class="container-flex-title">
      <div class="title">
        <ion-icon name="time-outline"></ion-icon>
        Minutes
      </div>
      <center><%= @recipe.cook_time %></center>
    </div>
    <div class="container-flex-title">
      <div class="title">
        <ion-icon name="book-outline"></ion-icon>
        Ingredients
      </div>
      <center><%=@recipe.recipe_ingredients.count  %></center>
    </div>
    <div class="container-flex-title">
      <div class="title">
        <ion-icon name="people-outline"></ion-icon>
        Servings</div>
      <center><%= @recipe.servings %></center>
    </div>
  </div>
</div>
</div>
<div class="row tab">
<div style="margin: auto;">
<button style="float:none" class="tablinks active" onclick="openCity(event, 'Ingredients')">Ingredients</button>
<button style="float:none" class="tablinks" onclick="openCity(event, 'Instructions')">Instructions</button>
</div>
</div>

<!-- Tab content -->
<div id="Ingredients" class="tabcontent" style="display:block" >
    <div class="col-sm-6" > <br>
      <%# <h2 class="text-left">Ingredients</h2> %>
      <% @ingredients.each do |ingredient| %>
        <% if ingredient.quantity.to_s[-1]=='0' %>
            <p><%= ingredient.quantity.round %>
          <% else %>
            <%= ingredient.quantity %>
          <% end %>
            <%= ingredient.unit %>
            <%= ingredient.ingredient.name %>  </p>
      <% end %>

    </div>
</div>

<div id="Instructions" class="tabcontent" >
   <div class="col-sm-6"><br>
      <%# <h2 class="text-left">Instructions</h2> %>
      <% @instructions.each do |instruction| %>
        <p><%= instruction %></p>
      <% end %>
    </div>
</div>

<hr>
<div class="container text" >
   <div class='social'>
    <%= social_share_button_tag('Check this recipe:', desc: @recipe.name) %>
   </div>
</div>
<hr>

</div>
</div>


<script>
function openCity(evt, cityName) {
// Declare all variables
var i, tabcontent, tablinks;

// Get all elements with class="tabcontent" and hide them
tabcontent = document.getElementsByClassName("tabcontent");
for (i = 0; i < tabcontent.length; i++) {
tabcontent[i].style.display = "none";
}

// Get all elements with class="tablinks" and remove the class "active"
tablinks = document.getElementsByClassName("tablinks");
for (i = 0; i < tablinks.length; i++) {
tablinks[i].className = tablinks[i].className.replace(" active", "");
}

// Show the current tab, and add an "active" class to the button that opened the tab
document.getElementById(cityName).style.display = "block";
evt.currentTarget.className += " active";
}
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <p>Created by:</p>
    <ul>
      <li><%= link_to "Brigildo | ", "https://github.com/Brigildo14", target: "_blank", rel: "nofollow" %></li>
      <li><%= link_to "Dev | ", "https://github.com/loperdev", target: "_blank", rel: "nofollow" %></li>
      <li><%= link_to "Marva | ", "https://github.com/marvoosh", target: "_blank", rel: "nofollow" %></li>
      <li><%= link_to "Thallia", "https://github.com/tliabr", target: "_blank", rel: "nofollow" %></li>
    </ul>
  </div>
  <div class="footer-img">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "chefme_trial_logo2_transparent_no_slogan.png" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>">

  <% if user_signed_in? %>

    <div class="navbar-left-div">
      <input type="checkbox" id="chec">
      <label for="chec">
        <%= image_tag "https://ca.slack-edge.com/T02NE0241-U02GFM63B8B-3067df17e3fa-512", class: "avatar dropdown-toggle", id: "navbarDropdown" %>
      </label>
      <nav>
        <ul>
          <li>
            <%= link_to dashboard_path, class: "navbar-brand" do %>
              <i class="fas fa-bookmark"></i> Saved
            <% end %>
          </li>
          <li>
            <%= link_to favourite_path, class: "navbar-brand" do %>
              <i class="fas fa-heart"></i> Favourites
            <% end %>
          </li>
          <li>
            <%= link_to completed_path, class: "navbar-brand" do %>
              <i class="fas fa-check-square"></i> Completed
            <% end %>
          </li>
          <li style="margin-top: 470px; border-bottom: 0px; border-top: 1px solid #F4F4F4;">
            <%= link_to destroy_user_session_path, method: :delete, class: "navbar-brand" do %>
              <i class="fas fa-sign-out-alt"></i> Log Out
            <% end %>
          </li>
        </ul>
      </nav>
    </div>

    <div style="width: 100px">
      <%= link_to recipes_path, class: "navbar-brand" do %>
        <%= image_tag "chefme_trial_logo2_transparent_no_slogan.png" %>
      <% end %>
    </div>

  <% else %>

    <div>
    </div>

    <div style="width: 100px">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "chefme_trial_logo2_transparent_no_slogan.png" %>
      <% end %>
    </div>

    <div>
    </div>

  <% end %>

</div>